
create table t_sip_dependente(
    cd_dependente number(3) not null,
    nm_dependente varchar2(50) not null,
    dt_nascimento date not null,
    nr_matricula number(5) not null
)

alter table t_sip_dependente add constraint pk_sip_dependente primary key (nr_matricula,cd_dependente);


CREATE TABLE T_SIP_PROJETO
(
CD_PROJETO NUMBER(5) NOT NULL,
NM_PROJETO VARCHAR2(40) NOT NULL,
DT_INICIO DATE NOT NULL,
DT_TERMINO DATE NULL
);

ALTER TABLE T_SIP_PROJETO ADD CONSTRAINT PK_SIP_PROJETO PRIMARY KEY(CD_PROJETO);

ALTER TABLE T_SIP_PROJETO ADD CONSTRAINT CK_SIP_PROJETO_DATA CHECK(DT_TERMINO > DT_INICIO);

drop table t_sip_projeto;


CREATE TABLE T_SIP_IMPLANTACAO
(
CD_PROJETO NUMBER(5) NOT NULL,
CD_IMPLANTACAO NUMBER(3) NOT NULL,
NR_MATRICULA NUMBER(5) NOT NULL,
DT_ENTRADA DATE NOT NULL,
DT_SAIDA DATE
);

ALTER TABLE T_SIP_IMPLANTACAO ADD CONSTRAINT PK_SIP_IMPLANTACAO PRIMARY KEY(CD_PROJETO,CD_IMPLANTACAO);

ALTER TABLE T_SIP_IMPLANTACAO ADD CONSTRAINT CK_SIP_IMPLANT_DATA CHECK(DT_SAIDA > DT_ENTRADA);


ALTER TABLE t_sip_funcionario
    ADD CONSTRAINT fk_sip_func_depto FOREIGN KEY ( cd_depto )
        REFERENCES t_sip_depto ( cd_depto );

ALTER TABLE t_sip_implantacao
    ADD CONSTRAINT fk_sip_implantacao_funcionario FOREIGN KEY ( nr_matricula )
        REFERENCES t_sip_funcionario ( nr_matricula );
        
ALTER TABLE T_SIP_IMPLANTACAO
    ADD CONSTRAINT FK_SIP_IMPLANTACAO_PROJETO FOREIGN KEY ( CD_PROJETO )
        REFERENCES T_SIP_PROJETO ( CD_PROJETO );
        
ALTER TABLE T_SIP_DEPENDENTE
    ADD CONSTRAINT FK_SIP_DEPENDENTE_FUNCIONARIO FOREIGN KEY ( NR_MATRICULA )
        REFERENCES T_SIP_FUNCIONARIO ( NR_MATRICULA );

